---
pipeline:
  build:
    image: golang
    commands:
      - cd outyet
      - go build
      - go test

  test:
    image: golang
    commands:
      - cd outyet
      - go test


  publish:
    gcr:
      repo: gcr.io/packetfield/example

