---
pipeline:
  compile:
    image: golang
    commands:
      - cd outyet
      - go build
      - go test

  # test:
  #   image: golang
  #   commands:
  #     - cd outyet
  #     - go test

  # publish:
  #   gcr:
  #     repo: gcr.io/packetfield/example
  #     tags:
  #       - "${DRONE_COMMIT_SHA:0:8}"
  #       - "${DRONE_BRANCH}"
  #       - "tag-${DRONE_TAG##v}"
  #     debug: true

      # when:
      #   branch: [master, develop]

