---
pipeline:
  compile:
    image: golang
    commands:
      - cd hello
      - go get
      - go build

  # test:
  #   image: golang
  #   commands:
  #     - cd outyet
  #     - go test

  publish:
    image: plugins/gcr
    repo: packetfield/example
    dockerfile: hello/Dockerfile
    tags:
      - latest
      - "${DRONE_BRANCH}"
      - "tag-${DRONE_TAG##v}"
    debug: false

    when:
      branch: [master, develop]

