---
pipeline:
  compile:
    image: golang
    commands:
      - cd outyet
      - go build

  test:
    image: golang
    commands:
      - cd outyet
      - go test

  publish:
    image: plugins/gcr
    repo: packetfield/example
    dockerfile: outyet/Dockerfile
    tags:
      - latest
      - "${DRONE_BRANCH}"
      - "tag-${DRONE_TAG##v}"
    debug: false
    secrets: [google_credentials]

    when:
      branch: [master, develop]

