---
pipeline:
  compile:
    image: golang
    commands:
      - cd outyet
      - go build
      - go test

  publish:
    image: plugins/gcr
    repo: packetfield/example
    tags:
      - latest
      - "${DRONE_BRANCH}"
      - "tag-${DRONE_TAG##v}"
    debug: true

    when:
      branch: [master, develop]

